### ISSUE TITLE
Basic player info in profile page

### ISSUE THREAD

**Issue by danfstucky** [danfstucky/LeagueSpec#22]
Now that it has been shown that the LoL API can successfully be integrated with the app, it is time to start constructing the profile page.  

As a user, I would like to see some basic stats of my profile.  
1) Which champion I play the most
2) Which champion do I have the highest Kill/Death ratio with
3) Which champion do I have the highest Win/Loss ratio with
4) My overall Kill/Death ratio (calculated from accumulated kills and deaths from every champion I have played)
5) My overall Win/Loss ratio  (calculated from accumulated kills and deaths from every champion I have played)
6) A link that will lead me to more detailed statistics for each individual champion.  For now this should simply route to a new page and the implementation will be handled in a separate issue.
7) This page should be designed in a way that creates a good user experience where the data is easy to view and visually pleasing to look at.

I am not too familiar with LoL, but I believe it has multiple gametypes and the above info can likely be retrieved separately for each gametype.  This issue ONLY applies to the Classic PvP game mode.  We can add options for viewing data for more game modes later if we want.

**Comment by sl7v3** [comment]
@danfstucky, my implementation of the KDR is Champion Kill / Deaths. There are KDR variations depending on what players consider important. Some KDR implementations account for minion kills too. If you have a specific KDR formula in mind, let me know. For now, I am using Champion Kills / Deaths.
Also in #6 of the issue, I assume individual champion is referring to the champions in the first three requirements. Clarify when you get a chance.

**Comment by danfstucky** [comment]
@sl7v3 Yes, only look at the champion kills/deaths.
We will have to store our own icons.  I think we would add the icons to the assets folder though, not in a db.  That will probably be a separate issue on its own.  For now you can just put text in its place unless you're feeling really ambitious.
