### ISSUE TITLE
Add Summoner Friend to Profile Page

### ISSUE THREAD

**Issue by sl7v3** [danfstucky/LeagueSpec#27]
As a logged-in user,
I would like to view my summoner friends on my profile page in an appearance similar to those on other social media sites.
Story is considered complete when:
1. After clicking "Add Friend" button on the page/pop-up with searched Friend information, friend request is sent.
2. After accepting the request, I can see the friend in my list of accepted/active friends.
3. Limit friend's list to 5 per page with option to click Next and proceed to next page.
4. Clicking on each picture in this grid takes me to the page/pop-up with information about the summoner friend.
5. Pages and prompts in steps above should be well-styled for good user experience.

**Comment by danfstucky** [comment]
Something cool is to also show the online status of your friends.  As an example, I made an android app that looked like this:
![screenshot_2016-06-26-12-33-43](https://cloud.githubusercontent.com/assets/13394759/16363764/73bbf568-3b9a-11e6-8c68-179f59b5d6bd.png)

Here are the icons i made to indicate status if you're interested:
![status_online](https://cloud.githubusercontent.com/assets/13394759/16363738/b353bd24-3b99-11e6-81f0-4fffeb608dc7.png)
![status_offline](https://cloud.githubusercontent.com/assets/13394759/16363739/b4b21760-3b99-11e6-8511-2a8b56069f0c.png)
![status_lobby](https://cloud.githubusercontent.com/assets/13394759/16363740/b6d9d870-3b99-11e6-9a6a-5364f647342a.png)

**Comment by sl7v3** [comment]
That's really cool. I'll look into it.

**Comment by sl7v3** [comment]
Currently, functionality has been implemented to add a friend, accept friendship, display all friends, pending requests.
Functionality is being implemented to display online friends and include visual icons to signify online status as shown in pictures above.
It should be ready no later than the weekend

**Comment by sl7v3** [comment]
@danfstucky this issue has a pull request that is available for review.

**Comment by sl7v3** [comment]
Functionality implemented and icons moved to another issue. Closed
