### ISSUE TITLE
Investigate slow Profile Page response times

### ISSUE THREAD

**Issue by danfstucky** [danfstucky/LeagueSpec#33]
It takes about 7 seconds to load the profile page right now, which drastically reduces user experience.  
Determine the cause for this poor performance and fix it if possible.
I suspect it is related to inefficient data retrieval from the LoL api.

**Comment by danfstucky** [comment]
After some investigation, this may be due in part to assets not being precompiled.  Further investigation still needed

**Comment by danfstucky** [comment]
Investigation Conclusions:
1) Precompiling assets has nothing to do with the problem
2) The profiles CSS and html is messy and needs optimizing.  As of right now, I have completed this step and was able to reduce total page load time by 0.5s.
3) The problem is almost entirely related to server side work (db data retrieval).
![network_profile](https://cloud.githubusercontent.com/assets/13394759/17197962/d546512a-5436-11e6-803f-7e20cde30e35.PNG)
The primary goal of this task is to now reduce the time spent on server.

**Comment by sl7v3** [comment]
Good!

**Comment by danfstucky** [comment]
[Merged](https://github.com/danfstucky/LeagueSpec/commit/83688605d5331bbfd69fae1de3307da953255740)
