### ISSUE TITLE
Integrate LoL Api into app

### ISSUE THREAD

**Issue by danfstucky** [danfstucky/LeagueSpec#8]

**Comment by danfstucky** [comment]
You will need to get the API key first.  Then import the gem and output some sort of basic operation from the api on to the profiles page to prove it is working.

**Comment by jwiebe17** [comment]
6e34404e-7d38-4efb-9219-2524c9c80ff7

api key 

 


 On Thu, Jan 7, 2016 at 9:06 PM, Dan Stucky<notifications@github.com> wrote:  Assigned #8 to @jwiebe17.—

**Comment by jwiebe17** [comment]
We should save it so I can delete the comment from github

**Comment by danfstucky** [comment]
@jwiebe17 
Store the key in a constant inside `config/secrets.yml`. 
Then setup `.gitignore` to not check the secrets file into github by default.  
Never post that information as it is all documented for the public to see.  You should delete your comment.

**Comment by danfstucky** [comment]
In fact, I think setting up `.gitignore` should be a separate issue.  There are a couple of things we should add to that.  Add the api key to secrets, but just work with it  locally until .gitignore is completed.

**Comment by sl7v3** [comment]
I have pushed a branch that pulls in information from the api and displays it on the profile page. I will send out a pull request for this. I will not be merging the pull request but for anyone who wants to see how it was done. I am also thinking we should re-arrange or re-organize tasks so we can move at a faster pace.
