### ISSUE TITLE
Mock out profiles page

### ISSUE THREAD

**Issue by danfstucky** [danfstucky/LeagueSpec#9]
We do not have access to any dynamic data as of yet so I would like a mock page to show how the profiles page will look.
This will make it easier to implement the dynamic content later on and give us a good first step to determining what we want on the page and how we want to display it.  

I know for sure we will need the player's name, friend's list, player's best champion, player's overall k/d, player's overall win/loss, basic stats for individual champions.
We may even place links on the page to lead to more in depth statistics of a player.
This issue is open for discussion.

**Comment by sl7v3** [comment]
This needs to either be closed or modified. After looking at the API a little, the profile might be lacking relevant information and might contain some irrelevant ones.

**Comment by danfstucky** [comment]
I will let you and Joel decide what is important.  Closing this
